SELECT HISTORY_ID, 
( ROUND(
    DAILY_FEE * (TIMESTAMPDIFF(DAY, START_DATE,END_DATE) + 1) * ((100 - IFNULL(DISCOUNT_RATE,0)) / 100)
    ,0)) AS FEE
FROM ( SELECT *, 
        CASE
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 7 THEN NULL
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 30 THEN '7일 이상'
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END DURATION_TYPE 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON C.CAR_ID = RH.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON RH.DURATION_TYPE = DP.DURATION_TYPE AND C.CAR_TYPE = DP.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC